### ISSUE TITLE
Android crash

### ISSUE THREAD

**Issue by snns334** [DasshuDev/BetterGauntlets#5]
https://github.com/user-attachments/assets/2c24eacb-dfe0-4ea2-80f7-c0509fa8dff5

**Comment by Vaulto350** [comment]
I disabled all my mods and it still crashes. So there's that to add to the issue.

**Comment by DasshuDev** [comment]
Fixed in the next update.

**Comment by DasshuDev** [comment]
Fixed in the next update.
